# Generated by Django 5.1.6 on 2025-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_shipment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="original_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
