# Generated by Django 5.1.6 on 2025-02-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_created_at_alter_product_buying_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
