# Generated by Django 5.1.6 on 2025-04-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_original_stock_product_sales_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="original_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales_stock",
        ),
    ]
