# Generated by Django 5.1.6 on 2025-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_product_original_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="original_stock",
            field=models.IntegerField(default=0),
        ),
    ]
