# Generated by Django 5.1.5 on 2025-02-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="lot_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
