# Generated by Django 5.1.6 on 2025-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item_code",
            field=models.CharField(max_length=100),
        ),
    ]
