# Generated by Django 5.1.6 on 2025-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_product_shipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shipment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
