# Generated by Django 5.1.6 on 2025-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_product_shipment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="critical_stock",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
