# Generated by Django 5.1.6 on 2025-02-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_sale_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="status",
        ),
    ]
