# Generated by Django 5.1.6 on 2025-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_sale_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
