# Generated by Django 5.1.6 on 2025-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_sale_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
