# Generated by Django 5.1.6 on 2025-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_sale_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(),
        ),
    ]
